language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update --preview
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer run cs
  - composer run test
